### ISSUE TITLE
Failed to read file as classpath

### ISSUE THREAD

**Issue by deshpandesagar** [bwanglzu/Automatic-Question-Generation#26]
Hi, I faced following issue..

java.io.IOException: Unable to open "/home/sagar/BE_Project_details/Codes/Moduloe_3/Automatic-Question-Generation/Standford-modelsenglishPCFG.ser.gz" as class path, filename or URL
  edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:480)
  edu.stanford.nlp.io.IOUtils.readStreamFromString(IOUtils.java:400)
  edu.stanford.nlp.parser.lexparser.LexicalizedParser.getParserFromSerializedFile(LexicalizedParser.java:598)
  edu.stanford.nlp.parser.lexparser.LexicalizedParser.getParserFromFile(LexicalizedParser.java:404)
  edu.stanford.nlp.parser.lexparser.LexicalizedParser.loadModel(LexicalizedParser.java:186)
  edu.stanford.nlp.parser.lexparser.LexicalizedParser.main(LexicalizedParser.java:1400)
java.io.IOException: Unable to open "/home/sagar/BE_Project_details/Codes/Moduloe_3/Automatic-Question-Generation/Standford-modelsenglishPCFG.ser.gz" as class path, filename or URL
	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:480)
	at edu.stanford.nlp.io.IOUtils.readerFromString(IOUtils.java:617)
	at edu.stanford.nlp.parser.lexparser.LexicalizedParser.getParserFromTextFile(LexicalizedParser.java:541)
	at edu.stanford.nlp.parser.lexparser.LexicalizedParser.getParserFromFile(LexicalizedParser.java:406)
	at edu.stanford.nlp.parser.lexparser.LexicalizedParser.loadModel(LexicalizedParser.java:186)
	at edu.stanford.nlp.parser.lexparser.LexicalizedParser.main(LexicalizedParser.java:1400)
Exception in thread "main" java.lang.NullPointerException
	at edu.stanford.nlp.parser.lexparser.LexicalizedParser.loadModel(LexicalizedParser.java:188)
	at edu.stanford.nlp.parser.lexparser.LexicalizedParser.main(LexicalizedParser.java:1400)

Traceback (most recent call last):
  File "app1.py", line 71, in <module>
    print pipeline(args.input)
  File "app1.py", line 44, in pipeline
    candidates = gs.get_candidates(sentences)
  File "/home/sagar/BE_Project_details/Codes/Moduloe_3/Automatic-Question-Generation/aqg/utils/gap_selection.py", line 84, in get_candidates
    tree = self._parse(sentence)
  File "/home/sagar/BE_Project_details/Codes/Moduloe_3/Automatic-Question-Generation/aqg/utils/gap_selection.py", line 41, in _parse
    parsed_sentence = list(parser.raw_parse((sentence)))
  File "/home/sagar/anaconda2/lib/python2.7/site-packages/nltk/parse/stanford.py", line 132, in raw_parse
    return next(self.raw_parse_sents([sentence], verbose))
  File "/home/sagar/anaconda2/lib/python2.7/site-packages/nltk/parse/stanford.py", line 150, in raw_parse_sents
    return self._parse_trees_output(self._execute(cmd, '\n'.join(sentences), verbose))
  File "/home/sagar/anaconda2/lib/python2.7/site-packages/nltk/parse/stanford.py", line 216, in _execute
    stdout=PIPE, stderr=PIPE)
  File "/home/sagar/anaconda2/lib/python2.7/site-packages/nltk/internals.py", line 134, in java
    raise OSError('Java command failed : ' + str(cmd))
OSError: Java command failed : [u'/usr/bin/java', u'-mx1000m', '-cp', '/home/sagar/BE_Project_details/Codes/Moduloe_3/Automatic-Question-Generation/Standford-models/stanford-parser-3.9.1-models.jar:/home/sagar/BE_Project_details/Codes/Moduloe_3/Automatic-Question-Generation/Standford-models/stanford-ner.jar:/home/sagar/BE_Project_details/Codes/Moduloe_3/Automatic-Question-Generation/Standford-models/stanford-parser-3.9.1-models.jar:/home/sagar/BE_Project_details/Codes/Moduloe_3/Automatic-Question-Generation/Standford-models/stanford-ner-3.9.1.jar:/home/sagar/BE_Project_details/Codes/Moduloe_3/Automatic-Question-Generation/Standford-models/stanford-parser.jar', u'edu.stanford.nlp.parser.lexparser.LexicalizedParser', u'-model', '/home/sagar/BE_Project_details/Codes/Moduloe_3/Automatic-Question-Generation/Standford-modelsenglishPCFG.ser.gz', u'-sentences', u'newline', u'-outputFormat', u'penn', u'-encoding', u'utf8', '/tmp/tmpjqorzy']

**Comment by deshpandesagar** [comment]
Resolved
