### ISSUE TITLE
NLTK was unable to find stanford-ner.jar! Set the CLASSPATH   environment variable.

### ISSUE THREAD

**Issue by deshpandesagar** [bwanglzu/Automatic-Question-Generation#27]
Hi, I got the following issue

Traceback (most recent call last):
  File "app1.py", line 71, in <module>
    print pipeline(args.input)
  File "app1.py", line 45, in pipeline
    fc = FeatureConstruction()
  File "/home/sagar/BE_Project_details/Codes/Moduloe_3/Automatic-Question-Generation/aqg/utils/feature_construction.py", line 21, in __init__
    self.st = StanfordNERTagger(self.model_path)
  File "/home/sagar/anaconda2/lib/python2.7/site-packages/nltk/tag/stanford.py", line 168, in __init__
    super(StanfordNERTagger, self).__init__(*args, **kwargs)
  File "/home/sagar/anaconda2/lib/python2.7/site-packages/nltk/tag/stanford.py", line 53, in __init__
    verbose=verbose)
  File "/home/sagar/anaconda2/lib/python2.7/site-packages/nltk/internals.py", line 719, in find_jar
    searchpath, url, verbose, is_regex))
  File "/home/sagar/anaconda2/lib/python2.7/site-packages/nltk/internals.py", line 714, in find_jar_iter
    raise LookupError('\n\n%s\n%s\n%s' % (div, msg, div))
LookupError: 

===========================================================================
  NLTK was unable to find stanford-ner.jar! Set the CLASSPATH
  environment variable.

  For more information, on stanford-ner.jar, see:
    <http://nlp.stanford.edu/software>

**Comment by bwanglzu** [comment]
Did you correctly set the configuration file (i.e. ,env)?
