### ISSUE TITLE
error wile running app.py

### ISSUE THREAD

**Issue by NSAryan12** [bwanglzu/Automatic-Question-Generation#30]
hey @bwanglzu, 

Its me again :)

so I moved the 'obama.txt' file from the test folder to the 'aqg folder' and when I run.

`python app.py -f obama.txt`

I get this error:
```
Traceback (most recent call last):
  File "app.py", line 72, in <module>
    print pipeline(args.input)
  File "app.py", line 42, in pipeline
    gs = GapSelection()
  File "/Users/aryan/Desktop/questiongen/Automatic-Question-Generation/aqg/utils/gap_selection.py", line 16, in __init__
    'STANFORD_JARS')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 473, in __setitem__
    putenv(key, item)
TypeError: must be string, not None

```

Any ideas?

Thanks

**Comment by bwanglzu** [comment]
@NSAryan12 it means it can't read the configuration in `.env`, did you configure that? If success it will pass a string to the code, but get a `None` at the moment.

**Comment by NSAryan12** [comment]
@bwanglzu,
I am pretty new to this.. 
where do you mean by "project root"? 
I think I have created it in the wrong place

**Comment by bwanglzu** [comment]
@NSAryan12 it means `your/path/to/Automatic-Question-Generation/`, the same directory as `README.md`

**Comment by NSAryan12** [comment]
right so this is what I did.

I `cd` to the project root.
then I typed: `touch .env`
after I typed: `open .env`

then I pasted this code in there and then I saved it:
```
SENTENCE_RATIO = 0.05 #The threshold of important sentences
STANFORD_JARS=/Users/aryan/Desktop/questiongen/stanford-models/
STANFORD_PARSER_CLASSPATH=/Users/aryan/Desktop/questiongen/stanford-models/stanford-parser-3.9.1-models.jar
STANFORD_NER_CLASSPATH=/Users/aryan/Desktop/questiongen/stanford-models/stanford-ner.jar
```


This is when I get the error I stated above.

am I doing things right?

Thanks a lot 
Aryan

**Comment by bwanglzu** [comment]
@NSAryan12 If you download the models & set the correct path, it should work :)

**Comment by NSAryan12** [comment]
@bwanglzu but it doesnt.
